### ISSUE TITLE
compilation and start up

### ISSUE THREAD

**Issue by Ciruman** [chriswhocodes/DemoFX#1]
Hi, 

I was trying to use the aplication and I had an error:
- after downloading the source code, I run the compilation: ant compile. Everithing right but then I try to start the application as expleined with run.sh I got that the class coudl not be found com.chrisnewland.demofx.DemoFXApplication

Cheers,
Diego

**Comment by chriswhocodes** [comment]
Hi,

Just run "ant". The default task should be jar and the run.sh script looks for DemoFX.jar on the classpath.

I'll update the README with the correct instructions.

Cheers,

Chris
